name: Staging CI

on:
  push:
    branches:
      - master
    tags:
      - '!refs/tags/*'

jobs:
  print_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Print
        run: |
          echo "Should not be trigered on release"
          echo "Branch - ${{ github.ref }}"