name: Staging CD

on:
  push:
    branches:
      - master
    tags:
      - '!refs/tags/*'

env:
  BRANCH: ${{ github.ref }}

jobs:
  print_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH }}

      - name: Print
        run: |
          echo "Should not be trigered on release"
          echo "Branch - ${{ env.BRANCH }}"