name: Staging CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/15 * * * *'

jobs:
  print_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH }}

      - name: Print
        run: echo "Branch - ${{ env.GITHUB_REF }}"